version: 1
disable_existing_loggers: False

formatters:
  json:
    '()': pythonjsonlogger.json.JsonFormatter
    format: "%(asctime)s %(levelname)s %(name)s %(module)s %(funcName)s %(lineno)d %(message)s"
  default:
    format: "%(levelprefix)s %(asctime)s - %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    '()': uvicorn.logging.DefaultFormatter

handlers:
  json_handler:
    formatter: json
    class: logging.StreamHandler
    stream: ext://sys.stdout
  console_handler:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  app:
    handlers: [json_handler]
    level: INFO
    propagate: False

  uvicorn.access:
    handlers: [json_handler]
    level: INFO
    propagate: False

  uvicorn.error:
    handlers: [json_handler]
    level: INFO
    propagate: False
